"""LongHorizonOS E2 — integrations (experimental v0.x).

Replaceable execution adapters (models, tools) that depend downward through the
public Core/SDK.  They do NOT own semantic truth; READY/VERIFIED/STALE/Goal CLOSED
remain VPG-derived.  Deleting this package must leave Core V1 semantics intact.
"""

from .harness import (
    DeepSeekHarnessAdapter,
    DeepSeekHarnessConfig,
    DeepSeekHarnessPhase,
    DeepSeekPatchRoute,
    DeepSeekRetryPolicy,
    HarnessBestCheckpoint,
    HarnessBestCheckpointStore,
    HarnessContinuationAction,
    HarnessContinuationDecision,
    HarnessEfficiencyDisposition,
    HarnessEfficiencyEstimate,
    HarnessEfficiencyGuardDecision,
    HarnessEfficiencyGuardObservation,
    HarnessExecutionBinding,
    HarnessFailure,
    HarnessFailureClass,
    HarnessPhaseEvent,
    HarnessPhaseKind,
    HarnessPhaseObservation,
    HarnessQualityObservation,
    HarnessRetryScope,
    HarnessUsage,
    QualityConstrainedEfficiencyGuard,
    SemanticContextPolicy,
    build_semantic_handoff,
    inspect_deepseek_patch,
    parse_deepseek_sessions,
)
from .models.openai_compatible import OpenAICompatibleModel
from .models.protocols import Message, ModelAdapter, ModelResponse
from .semantic import CommandVerifier
from .tools.git import GitTool
from .tools.provenance_http import (
    HTTPAccessDenied,
    HTTPGatewayError,
    HTTPObservation,
    HttpObservation,
    HTTPProvenanceGateway,
    HttpProvenanceGateway,
    HTTPRequest,
    HTTPResponseSnapshot,
    HTTPResponseValidationError,
    HTTPTransportError,
    HTTPVersionValidationError,
    canonical_http_url,
)
from .tools.provenance_workspace import (
    WorkspaceAccessDenied,
    WorkspaceGatewayError,
    WorkspaceProvenanceGateway,
    WorkspaceReadSetValidationError,
    WorkspaceReadSetValidationReport,
    WorkspaceSnapshot,
    WorkspaceVersionValidationError,
    WorkspaceVersionValidator,
)
from .tools.shell import ShellTool
from .tools.workspace import WorkspaceTool

__all__ = [
    "CommandVerifier",
    "DeepSeekHarnessAdapter",
    "DeepSeekHarnessConfig",
    "DeepSeekHarnessPhase",
    "DeepSeekPatchRoute",
    "DeepSeekRetryPolicy",
    "GitTool",
    "HTTPAccessDenied",
    "HTTPGatewayError",
    "HTTPObservation",
    "HTTPProvenanceGateway",
    "HTTPRequest",
    "HTTPResponseSnapshot",
    "HTTPResponseValidationError",
    "HTTPTransportError",
    "HTTPVersionValidationError",
    "HarnessBestCheckpoint",
    "HarnessBestCheckpointStore",
    "HarnessContinuationAction",
    "HarnessContinuationDecision",
    "HarnessEfficiencyDisposition",
    "HarnessEfficiencyEstimate",
    "HarnessEfficiencyGuardDecision",
    "HarnessEfficiencyGuardObservation",
    "HarnessExecutionBinding",
    "HarnessFailure",
    "HarnessFailureClass",
    "HarnessPhaseEvent",
    "HarnessPhaseKind",
    "HarnessPhaseObservation",
    "HarnessQualityObservation",
    "HarnessRetryScope",
    "HarnessUsage",
    "HttpObservation",
    "HttpProvenanceGateway",
    "Message",
    "ModelAdapter",
    "ModelResponse",
    "OpenAICompatibleModel",
    "QualityConstrainedEfficiencyGuard",
    "SemanticContextPolicy",
    "ShellTool",
    "WorkspaceAccessDenied",
    "WorkspaceGatewayError",
    "WorkspaceProvenanceGateway",
    "WorkspaceReadSetValidationError",
    "WorkspaceReadSetValidationReport",
    "WorkspaceSnapshot",
    "WorkspaceTool",
    "WorkspaceVersionValidationError",
    "WorkspaceVersionValidator",
    "build_semantic_handoff",
    "canonical_http_url",
    "inspect_deepseek_patch",
    "parse_deepseek_sessions",
]
